apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: blog-logs-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      name: blog-logs-volume